Repository DiLiubarets/LSD-project, pull requests merged in 2020-07, with the labels that each got.

#70 Added Dark Mode along with minor Light Mode fixes
  index.html
  myChart.js
  style.css
Labels: enhancement

#73 Darkmode sh1 - Darkmode fixes broken from previous merge
  index.html
  style.css
Labels: bug

#75 Podcast
  index.html
  myChart.js
  style.css
Labels: enhancement

#69 Update README.md
  README.md
Labels: documentation

#84 Darkmode sh2
  index.html
  myChart.js
Labels: bug

#86 Description scrollbar
  index.html
  style.css
Labels: enhancement

#88 Saves last viewed coin and candle
  myChart.js
Labels: enhancement

#89 Modal position
  coincap-logo-grey.jpg
  index.html
  style.css
Labels: bug

#91 Audio
  Dark mode.mp3
  Dropdown button.mp3
  index.html
  myChart.js
  navbar.mp3
Labels: enhancement

#96 Audio fix
  assets/contact form.mp3
  assets/dark mode.mp3
  assets/dropdown.mp3
  index.html
  myChart.js
  style.css
Labels: bug, enhancement
